Game: Thursday.o AaronsUtilities.o
	c++ AaronsUtilities.o Thursday.o ThursdayMain.cpp -o Thurs

Thursday.o: Thursday.cpp Thursday.h
	c++ -c Thursday.cpp

AaronsUtilities.o: AaronsUtilities.cpp AaronsUtilities.h
	c++ -c AaronsUtilities.cpp
		
clean:
	rm Thursday.o AaronsUtilities.o Thurs
