Game: Thursday.o Utilities.o
	c++ Utilities.o Thursday.o ThursdayMain.cpp -o Thurs

Thursday.o: Thursday.cpp Thursday.h
	c++ -c Thursday.cpp

AaronsUtilities.o: Utilities.cpp Utilities.h
	c++ -c Utilities.cpp
		
clean:
	rm Thursday.o Utilities.o Thurs
